<a href="https://colab.research.google.com/github/Promz/NumpyBasics/blob/main/numpybasic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array slicing and indexing
import numpy as np
arr_2=np.array([[1,2,3],[5,6,7]])
print(arr_2[1])
print(arr_2[1:])
#anything outside comma will be telling you about columns
print(arr_2[:,0])#it is considering this as column and will bring the entire value in that column

[5 6 7]
[[5 6 7]]
[1 5]


In [1]:
# Array reshaping and flattening
import numpy as np
arr1=np.array([1,2,3,4,5])
reshaped=arr1.reshape(5,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]
