<a href="https://colab.research.google.com/github/Promz/NumpyBasics/blob/main/numpybasic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array slicing and indexing
import numpy as np
arr_2=np.array([[1,2,3],[5,6,7]])
print(arr_2[1])
print(arr_2[1:])
#anything outside comma will be telling you about columns
print(arr_2[:,0])#it is considering this as column and will bring the entire value in that column

[5 6 7]
[[5 6 7]]
[1 5]


In [ ]:
# Array reshaping and flattening
import numpy as np
arr1=np.array([1,2,3,4,5])
reshaped=arr1.reshape(5,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
#Stacking
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
#Splitting
c=np.array([[1,2,3],[4,5,6]])
hsplit=np.hsplit(c,3)
vsplit=np.vsplit(c,3)
#print(split)
for s in hsplit:
  print(s)
for t in vsplit:
  print(t)

ValueError: array split does not result in an equal division

In [21]:
#Mathematical operations in Array
a=np.array([1,4,9])
b=np.array([2,5,10])
c=np.array([[7,8,9],[3,4,5]])
print(a)
print(a+10)
print(a-10)
print(np.square(a))
print(np.sqrt(a))
print(np.tan(a))
print(np.sin(a))
print(np.dot(a,b))# multiple all the value and then add them like 1*2+4*5+9*10
print(c.T)#converting rows to columns


[1 4 9]
[11 14 19]
[-9 -6 -1]
[ 1 16 81]
[1. 2. 3.]
[ 1.55740772  1.15782128 -0.45231566]
[ 0.84147098 -0.7568025   0.41211849]
112
[[7 3]
 [8 4]
 [9 5]]


In [ ]:
#Statistical functions in array