<a href="https://colab.research.google.com/github/Promz/NumpyBasics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
list1=[1,2,3]
print(list1)
arr_list1=np.array(list1)
print(arr_list1)

[1, 2, 3]
[1 2 3]


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
arr_list1_2=np.array([list1,list2])
print(arr_list1_2)
print(arr_list1_2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list1_2_3=np.array([[list1,list2,list3]])
print(arr_list1_2_3)
print(arr_list1_2_3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [ ]:
arr1=np.array([1,2,3])
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print(arr3)
print(arr1.ndim)
print(arr3.ndim)

[1 2 3]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
3


In [ ]:
# for zero array the elements are always 0
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Full array
full_arr=np.full((2,3),6)
print(full_arr)

[[6 6 6]
 [6 6 6]]


In [2]:
#Identity Matrices have their diagonal element always=0. It is always a 3*3 matrices
import numpy as np
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# empty array
print(np.empty(2))

[4.94065646e-324 6.82664691e-310]


In [6]:
#evenly spaced array
np.arange(2,10,2)

array([2, 4, 6, 8])

In [9]:
#specific number values between a range
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [13]:
#random values
np.random.rand(2,3)
np.random.randint(1,10,(3,3))

array([[6, 8, 3],
       [2, 1, 6],
       [1, 2, 3]])

In [ ]:
#Array Indexing and slicing